---
# output: github_document
output: 
  pdf_document:
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: svm-latex-ms.tex
    number_sections: true
title: | 
        | Estudio Profundo de la cuenca del Soco
        | Subtítulo
        | Subtítulo
author:
- name: "Isaac De La Rosa"
  affiliation: Afiliación, normalmente algo tal que "Estudiante Santo Domingo (UASD)"
abstract: "Resumen del manuscrito"
keywords: "palabra clave 1, palabra clave 2"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
# spacing: double
bibliography: bibliography.bib
# csl: plos-one.csl
csl: apa.csl
header-includes:
  \usepackage{pdflscape}
  \newcommand{\blandscape}{\begin{landscape}}
  \newcommand{\elandscape}{\end{landscape}}
  \usepackage{float} \floatplacement{figure}{H} 
  \newcommand{\beginsupplement}{
    \setcounter{table}{0}
    \renewcommand{\thetable}{S\arabic{table}}
    \setcounter{figure}{0}
    \renewcommand{\thefigure}{S\arabic{figure}}
    }
---

# Introducción
Si bien es cierto que cad vez que se hace un estudio de este tipo o relacionado a este, es en cierto sentido intermiable por la poca informacion ofrecida por las partes encargadas, pero tengo por seguro que este sera una inolvidable excepcion. En la republica Dominicana, existe una cuenta, una de las mas importantes en el este de dicho pais, el cual comprende desde la parte norte de la region este hasta el sur de dicha region, politicamente comienza desde la Provincia de El Seibo y la Provincia de Hato Mayor de el rey, en las zonas muy forestales y altas de la Cordillera del Seibo (coordillera oriental), y Dicha cuenca sera el punto de concentracion de nuestra investigacion.

Posee una forma en cierto sentido, normal, pensando el punto de desemboque, pero, ¿Posee algo mas que no sepamos? ¿que hace esta cuenca una de las mas importantes de la region?, ¿Existe o podria existir un area de estudio profundizado geomorfologicamente que impacto a la sociedad geografica latinoamericana o e mundo?


\ldots

# Metodología
Para esta investigacion hemos usado ciertos elementos de conocimiento presente en geografica, utilizados para estudio morfometrico de cuenta, como es el caso 
#blablabla sigo despues, i´m tired

\ldots

# Resultados

\ldots

# Discusión

# Agradecimientos

# Información de soporte

\ldots

# *Script* reproducible

\ldots

# Referencias
